export { WHISPER_TRANSCRIPTION_OPTIONS, TARTEEL_QURAN_MODEL, FALLBACK_WHISPER_MODEL } from "./whisperConfig";
export { QURAN_API_BASE_URL, QURAN_API_ENDPOINTS, QURAN_API_DEFAULT_PARAMS } from "./apiConfig";
export { DEFAULT_ELONGATION_SETTINGS } from "./elongationConfig";
